[package]
name = "cantara-slides"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.19.0", features = ["serde", "v7"] }

[dev-dependencies]
serde_json = "1.0.147"
